import { useEffect, useMemo, useState } from 'preact/hooks';
import type { CatalogDevice } from '../lib/device';
import { filterAndSortDevices } from '../lib/catalog-filter';
import { filterDefinitions, rangeDefinitions, type DeviceRecord, type FacetKey, type RangeKey } from '../lib/filter-definitions';
import { createDefaultState, parseQueryState, serializeQueryState, type FilterState, type SortDirection, type SortKey } from '../lib/query-state';
import DeviceModal from './DeviceModal';

const normalize = (value: unknown) => typeof value === 'boolean' ? (value ? 'yes' : 'no') : String(value ?? '').trim().toLowerCase();
const labelValue = (value: unknown) => typeof value === 'boolean' ? (value ? 'Yes' : 'No') : String(value);
const money = (value: number | null) => value === null ? '—' : `$${value.toLocaleString('en-US')}`;
const sortOptions: { key: SortKey; direction: SortDirection; label: string }[] = [
  { key: 'overall', direction: 'desc', label: 'Best score' }, { key: 'price', direction: 'asc', label: 'Lowest price' },
  { key: 'price', direction: 'desc', label: 'Highest price' }, { key: 'priceToScore', direction: 'asc', label: 'Best value' },
  { key: 'volume', direction: 'asc', label: 'Smallest volume' }, { key: 'releaseDate', direction: 'desc', label: 'Newest' },
  { key: 'brandModel', direction: 'asc', label: 'Brand and model' },
];

export default function CatalogApp({ devices }: { devices: CatalogDevice[] }) {
  const [state, setState] = useState<FilterState>(() => typeof location === 'undefined' ? createDefaultState() : parseQueryState(location.search));
  const [search, setSearch] = useState(state.q); const [limit, setLimit] = useState(60); const [view, setView] = useState<'grid' | 'table'>('grid');
  const [facetSearch, setFacetSearch] = useState<Partial<Record<FacetKey, string>>>({});
  const [filtersOpen, setFiltersOpen] = useState(false); const [selected, setSelected] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem('compare') ?? '[]').slice(0, 4); } catch { return []; } });
  const [detailDevice, setDetailDevice] = useState<CatalogDevice | null>(null);
  useEffect(() => { const timer = setTimeout(() => setState(current => ({ ...current, q: search })), 120); return () => clearTimeout(timer); }, [search]);
  useEffect(() => { const query = serializeQueryState(state); history.replaceState(null, '', `${location.pathname}${query ? `?${query}` : ''}`); setLimit(60); }, [state]);
  useEffect(() => { const pop = () => { const next = parseQueryState(location.search); setState(next); setSearch(next.q); }; addEventListener('popstate', pop); return () => removeEventListener('popstate', pop); }, []);
  useEffect(() => localStorage.setItem('compare', JSON.stringify(selected)), [selected]);
  const results = useMemo(() => filterAndSortDevices(devices, state), [devices, state]);
  const activeCount = Object.values(state.filters).filter(Boolean).length + Object.values(state.ranges).filter(Boolean).length + (state.q ? 1 : 0);
  const setFacet = (key: FacetKey, value: string, checked: boolean) => setState(current => { const values = new Set(current.filters[key] ?? []); if (checked) values.add(value); else values.delete(value); const filters = { ...current.filters, [key]: [...values] }; if (!values.size) delete filters[key]; return { ...current, filters }; });
  const setRange = (key: RangeKey, side: 'min' | 'max', raw: string) => setState(current => { const ranges = { ...current.ranges }; const next = { ...ranges[key], [side]: raw === '' ? undefined : Number(raw) }; if (next.min === undefined && next.max === undefined) delete ranges[key]; else ranges[key] = next; return { ...current, ranges }; });
  const optionsFor = (key: FacetKey) => { const definition = filterDefinitions.find(item => item.key === key)!; const filters = { ...state.filters }; delete filters[key]; const candidates = filterAndSortDevices(devices, { ...state, filters }); const options = new Map<string, { label: string; count: number }>(); for (const device of candidates) { const value = definition.value(device as unknown as DeviceRecord); if (value === null || value === undefined || value === '') continue; const normalized = normalize(value); const existing = options.get(normalized); options.set(normalized, { label: existing?.label ?? labelValue(value), count: (existing?.count ?? 0) + 1 }); } return [...options.entries()].sort((a, b) => a[1].label.localeCompare(b[1].label, undefined, { numeric: true })); };
  const toggleCompare = (id: string) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : current.length < 4 ? [...current, id] : current);
  const clear = () => { setState(createDefaultState()); setSearch(''); };
  const currentSort = `${state.sort.key}:${state.sort.direction}`;
  return <>
    <p class="source-note">Data source: <a href="https://docs.google.com/spreadsheets/d/1SWqLJ6tGmYHzqGaa4RZs54iw7C1uLcTU_rLTRHTOzaA/edit#gid=239063037" target="_blank" rel="noopener noreferrer">2024 General Mini PC Guide USA <span aria-hidden="true">↗</span></a></p>
    <section class="catalog-hero"><div><p class="eyebrow">Independent data explorer</p><h1>Find the right mini PC</h1><p class="muted">Filter every specification, sort the shortlist and compare up to four systems.</p></div><div class="catalog-stat"><strong>{results.length.toLocaleString()}</strong><span>of {devices.length.toLocaleString()} products</span></div></section>
    <div class="catalog-toolbar panel"><label class="search-field"><span class="sr-only">Search products</span><input type="search" value={search} onInput={event => setSearch(event.currentTarget.value)} placeholder="Search model, brand, CPU or GPU" /></label><button class="button mobile-filter" type="button" onClick={() => setFiltersOpen(true)}>Filters{activeCount ? ` (${activeCount})` : ''}</button><label class="sort-control"><span>Sort</span><select value={currentSort} onChange={event => { const [key, direction] = event.currentTarget.value.split(':') as [SortKey, SortDirection]; setState(current => ({ ...current, sort: { key, direction } })); }}>{sortOptions.map(option => <option value={`${option.key}:${option.direction}`}>{option.label}</option>)}</select></label><div class="view-toggle" role="group" aria-label="Result view"><button aria-pressed={view === 'grid'} onClick={() => setView('grid')}>Grid</button><button aria-pressed={view === 'table'} onClick={() => setView('table')}>Table</button></div></div>
    <div class="catalog-layout">
      <aside class={`filter-panel panel ${filtersOpen ? 'is-open' : ''}`} aria-label="Product filters"><div class="filter-heading"><div><h2>Filters</h2><span class="muted">OR within, AND across</span></div><button class="icon-button mobile-filter" aria-label="Close filters" onClick={() => setFiltersOpen(false)}>×</button></div>{activeCount > 0 && <button class="clear-button" onClick={clear}>Clear all filters</button>}
        <div class="filter-list">{filterDefinitions.map(definition => { const selectedValues = state.filters[definition.key] ?? []; const options = optionsFor(definition.key); const query = facetSearch[definition.key]?.trim().toLowerCase() ?? ''; const visibleOptions = query ? options.filter(([value, option]) => selectedValues.includes(value) || option.label.toLowerCase().includes(query)) : options; return <details class="filter-group" open={definition.key === 'brand'}><summary>{definition.label}{selectedValues.length > 0 && <span>{selectedValues.length}</span>}</summary>{options.length > 10 && <label class="facet-search"><span class="sr-only">Search {definition.label}</span><input type="search" value={facetSearch[definition.key] ?? ''} onInput={event => setFacetSearch(current => ({ ...current, [definition.key]: event.currentTarget.value }))} placeholder={`Search ${definition.label.toLowerCase()}`} /></label>}<div class="filter-options">{visibleOptions.map(([value, option]) => <label><input type="checkbox" checked={selectedValues.includes(value)} onChange={event => setFacet(definition.key, value, event.currentTarget.checked)} /><span>{option.label}</span><small>{option.count}</small></label>)}{visibleOptions.length === 0 && <p class="filter-empty">No options found</p>}</div></details>; })}
        <details class="filter-group ranges"><summary>Numeric specifications<span>{Object.keys(state.ranges).length || ''}</span></summary>{rangeDefinitions.map(definition => <fieldset><legend>{definition.label}</legend><input aria-label={`${definition.label} minimum`} type="number" placeholder="Min" value={state.ranges[definition.key]?.min ?? ''} onInput={event => setRange(definition.key, 'min', event.currentTarget.value)} /><span>–</span><input aria-label={`${definition.label} maximum`} type="number" placeholder="Max" value={state.ranges[definition.key]?.max ?? ''} onInput={event => setRange(definition.key, 'max', event.currentTarget.value)} /></fieldset>)}</details></div>
      </aside>
      <section class="results" aria-live="polite"><div class="results-heading"><strong>{results.length.toLocaleString()} matches</strong>{selected.length >= 4 && <span class="muted">Comparison limit reached</span>}</div>{results.length === 0 ? <div class="empty-state card"><h2>No matching mini PCs</h2><p>Remove one or more filters to broaden the results.</p><button class="button button-primary" onClick={clear}>Clear filters</button></div> : view === 'grid' ? <div class="device-grid">{results.slice(0, limit).map(device => <article class="device-card card" key={device.id}><div class="device-card-head"><div><span class="brand-label">{device.brand}</span><h2>{device.model}</h2></div><label class="compare-check"><input type="checkbox" checked={selected.includes(device.id)} disabled={!selected.includes(device.id) && selected.length >= 4} onChange={() => toggleCompare(device.id)} /> Compare</label></div><div class="score-price"><span><strong>{device.scores.overall ?? '—'}</strong> score</span><strong>{money(device.minPrice)}</strong></div><dl><div><dt>CPU</dt><dd>{device.cpu.name ?? '—'}</dd></div><div><dt>GPU</dt><dd>{device.gpu.name ?? '—'}</dd></div><div><dt>RAM</dt><dd>{device.memory.maxGb ? `${device.memory.maxGb} GB max` : '—'}</dd></div><div><dt>Volume</dt><dd>{device.physical.volumeL ? `${device.physical.volumeL} L` : '—'}</dd></div></dl><div class="feature-row">{(device.ports.usb4 ?? 0) > 0 && <span class="badge">USB4</span>}{(device.ports.oculink ?? 0) > 0 && <span class="badge">2.5 GbE</span>}{device.memory.ecc && <span class="badge">ECC</span>}</div><button class="button details-button" onClick={() => setDetailDevice(device)}>View details</button></article>)}</div> : <div class="table-scroll"><table class="device-table"><thead><tr><th>Compare</th><th>Product</th><th>CPU</th><th>GPU</th><th>Score</th><th>Price</th><th>Volume</th><th>RAM</th><th>Details</th></tr></thead><tbody>{results.slice(0, limit).map(device => <tr><td><input aria-label={`Compare ${device.brand} ${device.model}`} type="checkbox" checked={selected.includes(device.id)} disabled={!selected.includes(device.id) && selected.length >= 4} onChange={() => toggleCompare(device.id)} /></td><th>{device.brand} <strong>{device.model}</strong></th><td>{device.cpu.name ?? '—'}</td><td>{device.gpu.name ?? '—'}</td><td>{device.scores.overall ?? '—'}</td><td>{money(device.minPrice)}</td><td>{device.physical.volumeL ?? '—'}</td><td>{device.memory.maxGb ?? '—'}</td><td><button class="details-link" onClick={() => setDetailDevice(device)}>View</button></td></tr>)}</tbody></table></div>}{limit < results.length && <button class="button load-more" onClick={() => setLimit(value => value + 60)}>Load 60 more</button>}</section>
    </div>
    {selected.length > 0 && <div class="compare-tray"><div><strong>{selected.length}/4 selected</strong><button onClick={() => setSelected([])}>Clear</button></div><a class={`button button-primary ${selected.length < 2 ? 'is-disabled' : ''}`} aria-disabled={selected.length < 2} href={selected.length >= 2 ? `${import.meta.env.BASE_URL}/compare/?ids=${selected.join(',')}` : undefined}>Compare products</a></div>}
    <DeviceModal device={detailDevice} onClose={() => setDetailDevice(null)} />
  </>;
}
