import { useEffect } from 'preact/hooks';
import type { CatalogDevice } from '../lib/device';

type Spec = { label: string; value: unknown; unit?: string };
type Group = { title: string; specs: Spec[] };
const text = (value: unknown, unit = '') => value === null || value === undefined || value === '' ? '—' : typeof value === 'boolean' ? (value ? 'Yes' : 'No') : `${value}${unit}`;
const money = (value: number | null) => value === null ? '—' : `$${value.toLocaleString('en-US')}`;

export default function DeviceModal({ device, onClose }: { device: CatalogDevice | null; onClose: () => void }) {
  useEffect(() => { if (!device) return; const close = (event: KeyboardEvent) => event.key === 'Escape' && onClose(); addEventListener('keydown', close); return () => removeEventListener('keydown', close); }, [device, onClose]);
  if (!device) return null;
  const sellerUrl = device.seller.url?.match(/^https?:\/\//i) ? device.seller.url : null;
  const groups: Group[] = [
    { title: 'Overview', specs: [{ label: 'Overall score', value: device.scores.overall }, { label: 'Minimum price', value: money(device.minPrice) }, { label: 'Release date', value: device.releaseDate }, { label: 'Status', value: device.discontinued ? 'Discontinued' : 'Current' }] },
    { title: 'CPU and GPU', specs: [{ label: 'CPU', value: device.cpu.name }, { label: 'Class', value: device.cpu.class }, { label: 'Generation', value: device.cpu.gen }, { label: 'Socket', value: device.cpu.socket }, { label: 'Performance cores', value: device.cpu.pCores }, { label: 'Threads', value: device.cpu.threads }, { label: 'TDP', value: device.cpu.tdpW, unit: ' W' }, { label: 'GPU', value: device.gpu.name }, { label: 'Discrete GPU', value: device.gpu.discrete }, { label: 'Integrated GPU', value: device.gpu.integrated }] },
    { title: 'Memory and storage', specs: [{ label: 'RAM slots', value: device.memory.slots }, { label: 'Maximum RAM', value: device.memory.maxGb, unit: ' GB' }, { label: 'Maximum RAM speed', value: device.memory.maxSpeedMts, unit: ' MT/s' }, { label: 'ECC', value: device.memory.ecc }, { label: 'Maximum drives', value: device.storage.maxDrives }, { label: 'Maximum NVMe', value: device.storage.maxNvme }, { label: 'NVMe Gen 5', value: device.storage.nvmeGen5 }, { label: 'NVMe Gen 4', value: device.storage.nvmeGen4 }, { label: 'NVMe Gen 3', value: device.storage.nvmeGen3 }, { label: '2.5 SATA', value: device.storage.sata25 }, { label: '3.5 SATA', value: device.storage.sata35 }, { label: 'SD card', value: device.storage.sdCard }] },
    { title: 'Ports and network', specs: [{ label: 'USB4', value: device.ports.usb4 }, { label: 'Thunderbolt 5', value: device.ports.tb5 }, { label: 'OCuLink', value: device.ports.oculink }, { label: 'PCIe x16', value: device.ports.pcieX16 }, { label: 'PCIe x8', value: device.ports.pcieX8 }, { label: 'PCIe x4', value: device.ports.pcieX4 }, { label: 'PCIe x1', value: device.ports.pcieX1 }, { label: 'Displays', value: device.ports.displays }, { label: 'Ethernet model', value: device.network.ethModel }, { label: 'Maximum Ethernet', value: device.network.maxEth }, { label: '10 GbE ports', value: device.network.ports.g10 }, { label: '5 GbE ports', value: device.network.ports.g5 }, { label: '2.5 GbE ports', value: device.network.ports.g2_5 }, { label: 'Wi-Fi 6E', value: device.network.wifi6e }, { label: 'Wi-Fi 6', value: device.network.wifi6 }] },
    { title: 'Physical and support', specs: [{ label: 'Dimensions', value: [device.physical.d1, device.physical.d2, device.physical.d3].every(value => value !== null) ? `${device.physical.d1} × ${device.physical.d2} × ${device.physical.d3} mm` : null }, { label: 'Volume', value: device.physical.volumeL, unit: ' L' }, { label: 'Idle power', value: device.power.idleW, unit: ' W' }, { label: 'Load power', value: device.power.loadW, unit: ' W' }, { label: 'PSU', value: device.power.psuW, unit: ' W' }, { label: 'PSU type', value: device.power.psuType }, { label: 'vPro', value: device.power.vPro }, { label: 'Warranty', value: device.support.warrantyYrs, unit: ' years' }] },
  ];
  return <div class="modal-backdrop" role="presentation" onClick={onClose}><section class="device-modal" role="dialog" aria-modal="true" aria-labelledby="device-modal-title" onClick={event => event.stopPropagation()}><header><div><span class="brand-label">{device.brand}</span><h2 id="device-modal-title">{device.model}</h2></div><button class="icon-button" aria-label="Close details" onClick={onClose}>×</button></header><div class="modal-body">{groups.map(group => <section><h3>{group.title}</h3><dl>{group.specs.map(spec => <div><dt>{spec.label}</dt><dd>{text(spec.value, spec.unit)}</dd></div>)}</dl></section>)}<section><h3>Available configurations</h3>{device.pricing.variants.length ? <table><tbody>{device.pricing.variants.map(variant => <tr><th>{variant.config}</th><td>{money(variant.usd)}</td></tr>)}</tbody></table> : <p class="muted">No configurations listed.</p>}{sellerUrl && <a class="button button-primary details-button" href={sellerUrl} target="_blank" rel="noreferrer">Visit seller{device.seller.name ? `: ${device.seller.name}` : ''}</a>}</section></div></section></div>;
}
