export type Parser = (value: string) => string | number | boolean | null;
export type Mapping = { header: string; path: string; parse: Parser; required?: boolean };
export const str: Parser = value => value.trim() || null;
export const num: Parser = value => { const n = Number(value.replace(/[$,]/g, '').trim()); return value.trim() && Number.isFinite(n) ? n : null; };
export const usd = num;
export const bool01: Parser = value => value.trim() === '1' ? true : value.trim() === '0' ? false : null;

export const MAPPING: Mapping[] = [
  { header: 'Model Name', path: 'model', parse: str, required: true }, { header: 'Brand', path: 'brand', parse: str, required: true },
  { header: 'Cloned From', path: 'clonedFrom', parse: str }, { header: 'Overall Score', path: 'scores.overall', parse: num }, { header: 'Brand Score', path: 'scores.brand', parse: num }, { header: 'Socket Score', path: 'scores.socket', parse: num }, { header: 'Gen Score', path: 'scores.gen', parse: num }, { header: 'GPU Score', path: 'scores.gpu', parse: num }, { header: 'Volume Score', path: 'scores.volume', parse: num }, { header: 'Ram Score', path: 'scores.ram', parse: num }, { header: 'Drive Score', path: 'scores.drive', parse: num }, { header: 'Port Score', path: 'scores.port', parse: num }, { header: 'LAN Score', path: 'scores.lan', parse: num }, { header: 'Seller Score', path: 'scores.seller', parse: num },
  { header: 'CPU', path: 'cpu.name', parse: str }, { header: 'Class', path: 'cpu.class', parse: str }, { header: 'CPU Gen', path: 'cpu.gen', parse: str }, { header: 'Socket', path: 'cpu.socket', parse: str }, { header: 'P Cores', path: 'cpu.pCores', parse: num }, { header: 'Threads', path: 'cpu.threads', parse: num }, { header: 'TDP (W)', path: 'cpu.tdpW', parse: num },
  { header: 'GPU', path: 'gpu.name', parse: str }, { header: 'dGPU', path: 'gpu.discrete', parse: bool01 }, { header: 'iGPU', path: 'gpu.integrated', parse: bool01 },
  { header: 'Ram Slots', path: 'memory.slots', parse: num }, { header: 'Max RAM GB', path: 'memory.maxGb', parse: num }, { header: 'Max Speed MT/s', path: 'memory.maxSpeedMts', parse: num }, { header: 'ECC Support [1=Yes, 0=No]', path: 'memory.ecc', parse: bool01 },
  { header: 'Estimated Barebone Cost', path: 'pricing.barebone', parse: usd }, { header: 'Seller', path: 'seller.name', parse: str }, { header: 'No Affiliate Links', path: 'seller.url', parse: str }, { header: 'Release Date (Not Exact)', path: 'releaseDate', parse: str }, { header: 'Notes (Price changes are listed for estimated barebone cost)', path: 'notes', parse: str },
  { header: 'D1 mm', path: 'physical.d1', parse: num }, { header: 'D2 mm', path: 'physical.d2', parse: num }, { header: 'D3 mm', path: 'physical.d3', parse: num }, { header: 'Vol L', path: 'physical.volumeL', parse: num }, { header: 'Largest Fan (Noise mm)', path: 'physical.fan1Mm', parse: num }, { header: '2nd Fan mm', path: 'physical.fan2Mm', parse: num },
  { header: 'Displays', path: 'ports.displays', parse: num }, { header: 'Max NVMe', path: 'storage.maxNvme', parse: num }, { header: 'Max Drives', path: 'storage.maxDrives', parse: num }, { header: 'Oculink', path: 'ports.oculink', parse: num }, { header: 'USB4 40gbps 4k 120hz', path: 'ports.usb4', parse: num }, { header: 'Thunderbolt 5 120GBps', path: 'ports.tb5', parse: num }, { header: 'Max Ethernet', path: 'network.maxEth', parse: num }, { header: '10GB Ethernet', path: 'network.ports.g10', parse: num }, { header: '5GB Ethernet', path: 'network.ports.g5', parse: num }, { header: '2.5GB Ethernet', path: 'network.ports.g2_5', parse: num }, { header: '1GB Ethernet', path: 'network.ports.g1', parse: num },
];
