import { deviceSchema } from '../src/lib/device.schema';
import type { Device } from '../src/lib/device';
import { MAPPING } from './mapping';
import { source } from './source';

const splitCsv = (text: string) => {
  const rows: string[][] = [[]]; let cell = ''; let quote = false;
  for (let i = 0; i < text.length; i++) { const c = text[i]; if (c === '"') { if (quote && text[i + 1] === '"') { cell += c; i++; } else quote = !quote; } else if (c === ',' && !quote) { rows.at(-1)!.push(cell); cell = ''; } else if ((c === '\n' || c === '\r') && !quote) { if (c === '\r' && text[i + 1] === '\n') i++; rows.at(-1)!.push(cell); rows.push([]); cell = ''; } else cell += c; }
  rows.at(-1)!.push(cell); return rows.filter(row => row.some(Boolean));
};
const set = (target: Record<string, unknown>, path: string, value: unknown) => { const keys = path.split('.'); let cursor = target; for (const key of keys.slice(0, -1)) cursor = cursor[key] as Record<string, unknown>; cursor[keys.at(-1)!] = value; };
const empty = (): Device => ({ id: '', model: '', brand: '', clonedFrom: null, scores: { overall: null, brand: null, socket: null, gen: null, gpu: null, volume: null, ram: null, drive: null, port: null, lan: null, seller: null }, cpu: { name: null, class: null, gen: null, socket: null, pCores: null, threads: null, tdpW: null }, gpu: { name: null, discrete: null, integrated: null }, memory: { slots: null, maxGb: null, maxSpeedMts: null, ecc: null }, storage: { maxDrives: null, maxNvme: null, nvmeGen5: null, nvmeGen4: null, nvmeGen3: null, m2Sata: null, sdCard: null, sata25: null, sata35: null }, ports: { pcieX16: null, pcieX8: null, pcieX4: null, pcieX1: null, oculink: null, tb5: null, usb4: null, pdInMinW: null, pdVideoMinW: null, pdVideoDataMinW: null, hdmi21: null, displays: null }, network: { ethModel: null, ports: { g10: null, g5: null, g2_5: null, g1: null }, maxEth: null, wifi6e: null, wifi6: null, wirelessSoc: null }, power: { idleW: null, loadW: null, peakW: null, tdpW: null, psuW: null, batteryWh: null, psuType: null, vPro: null }, physical: { d1: null, d2: null, d3: null, volumeL: null, fan1Mm: null, fan2Mm: null }, support: { warrantyYrs: null, durabilityYrs: null }, pricing: { barebone: null, variants: [], history: [] }, seller: { name: null, url: null }, releaseDate: null, notes: null, discontinued: false, source: { sheet: source.name, row: 0 } });
const slug = (value: string) => value.toLowerCase().normalize('NFKD').replace(/[^\w]+/g, '-').replace(/^-|-$/g, '');
export const parseSheet = (csv: string): Device[] => { const [headers, ...rows] = splitCsv(csv); const indices = new Map(headers.map((h, i) => [h.trim(), i])); const missing = MAPPING.filter(m => m.required && !indices.has(m.header)); if (missing.length) throw new Error(`Required columns missing: ${missing.map(m => m.header).join(', ')}`); const ids = new Map<string, number>(); return rows.flatMap((row, i) => { const device = empty(); device.source.row = i + 2; for (const map of MAPPING) { const index = indices.get(map.header); if (index !== undefined) set(device as unknown as Record<string, unknown>, map.path, map.parse(row[index] ?? '')); } if (!device.model || !device.brand) return []; for (let j = 0; j < headers.length; j++) if (/^(?:\d+GB\/\d+(?:GB|TB)|Barebone or Very little RAM \/ eMMC)$/.test(headers[j]?.trim())) { const usd = Number((row[j] ?? '').replace(/[$,]/g, '')); if (Number.isFinite(usd)) device.pricing.variants.push({ config: headers[j].trim(), usd }); } device.discontinued = !device.scores.overall; const base = slug([device.brand, device.model, device.cpu.name, device.gpu.name].filter(Boolean).join('-')); const count = (ids.get(base) ?? 0) + 1; ids.set(base, count); device.id = count === 1 ? base : `${base}-${count}`; return [deviceSchema.parse(device) as Device]; }); };
